.\" Modified from man(1) of FreeBSD, the NetBSD mdoc.template, and mdoc.samples.
.\" See Also:
.\" man mdoc.samples for a complete listing of options
.\" man mdoc for the short list of editing options
.\" /usr/share/misc/mdoc.template
.Dd 4/1/12               \" DATE 
.Dt getloc 1             \" Program name and manual section number 
.Os Darwin
.Sh NAME                 \" Section Header 
.Nm getloc
.\" Use .Nm macro to designate other names for the documented program.
.Nd Acquires the user's geolocation using either IP geocoding or Apple's CoreLocation.
.Sh SYNOPSIS             \" Section Header
.Nm
.Op Fl achlmprv          \" [-achlmprv]
.Op Fl t Ar seconds      \" [-t seconds] 
.Sh DESCRIPTION          \" Section Header
When using the IP geocoding option,
.Nm
first acquires the user's external IP address, then their geolocation via IP geocoding.
.Pp
When using Apple's CoreLocation,
.Nm
first acquires the user's latitude and longitude, then their geolocation via reverse geocoding.
.Pp
Either of the above options may be more accurate than the other, depending on the circumstances.
.Pp
If no options are specified, the user's external IP address, latitude, longitude, city, region, and country are displayed, all with preceding labels.
.Pp
The following options are available:
.Bl -tag -width -indent  /" Begins the list
.It Cm -a or --ipaddress
Prints the user's external IPv4 address on one line.
.It Cm -c or --country
Prints the user's two-digit country code on one line.
.It Cm -h or --help
Prints a short "help" screen on usage and options.
.It Cm -l or --labels
Before each component of the user's location, output a descriptive label. Ignored if it is the only option specified.
.It Cm -m or --city
Prints the user's city on one line.
.It Cm -p or --position
Prints the user's latitude/longitude position on two lines if
.Cm -l
is specified, or on one comma-delimited line otherwise.
.It Cm -r or --region
Prints the user's two-digit region code or, if not applicable, the full text of their region (i.e. state, province, etc.) on one line.
.It Cm -v or --verbose
Prints verbose output as the program progresses through finding the user's geolocation.
.It Cm -t or --timeout
Sets the timeout, in seconds, for attempting to acquire the user's location.
.El                      \" Ends the list
.Pp
.Sh LIMITATIONS          \" Known limitations or incomplete features
The user must have a functional Internet connection for
.Nm
to function.
.Pp
Currently, only IP geocoding is fully supported. Stubs for using Apple's CoreLocation are present, but not fully implemented.
